### ISSUE TITLE
pH not exported from Unitful

### ISSUE THREAD

**Issue by kleinschmidt** [JuliaBrewing/UnitfulBrew.jl#2]
I don't think it's necessary to use an alternative symbol for pH since while Unitful defines a unit called `pH`, it's not exported so there's no collision unless someone has explicitly imported it (IIRC this is by design, none of the actual units are exported so they can be pulled in only as needed).

```julia
julia> using Unitful

julia> pH
ERROR: UndefVarError: pH not defined
```

**Comment by rmsrosa** [comment]
Yes, that alternate symbol for pH is really bothering me. I agree we should keep `pH`.

**Comment by rmsrosa** [comment]
Hmm, if we just run `pH`, then it is undefined, just like `mg` is undefined. One needs a unit or a quantity, like

```julia
julia> using Unitful

julia> mg
ERROR: UndefVarError: mg not defined

julia> u"pH"
pH
```

So, the unit `u"pH"` is indeed exported. :( (I might have checked that when I came up with the other symbols.)

Anyway, one way out is to import only selected units, leaving "their" `pH` out, which is not going to be useful for us, along with many others. I think I've seen a way to do this at once for "usual" units.  I will look at that.

And we could keep `pH+` along with `pH`, just in case.

What do you say?

**Comment by kleinschmidt** [comment]
Ah yeah I guess I didn't understand how unitful worked then.  I think you'd have to re-define the `@u_str` macro to mask their units.  Might be worth asking about on slack/discourse.

**Comment by rmsrosa** [comment]
> Anyway, one way out is to import only selected units, leaving "their" pH out, which is not going to be useful for us, along with many others. I think I've seen a way to do this at once for "usual" units. I will look at that.

Looking at [Important note on namespaces](https://painterqubits.github.io/Unitful.jl/stable/#Important-note-on-namespaces) I thought at first that doing  `using Unitful.DefaultSymbols` would avoid conflict with the pico-Henry unit `pH`, but it doesn't. So I guess we will have to live with `u"pH+"` or `u"pwrH`, or something like that.
